version: "3.9"
services: 
  spring:
    build: .
    ports:
      - "8080:8080"
    links:
      - redis
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data